def CNN():
    global tf_X
    global tfidf_X
    global wordvec_X
    Y1 = to_categorical(Y)
    X_train, X_test, y_train, y_test = train_test_split(tf_X, Y1, test_size=0.3, random_state=0)
    cnn_model = Sequential()
    cnn_model.add(Dense(100, input_shape=(X_train.shape[1],)))
    cnn_model.add(Activation('relu'))
    cnn_model.add(Dropout(0.3))
    cnn_model.add(Dense(100))
    cnn_model.add(Activation('relu'))
    cnn_model.add(Dropout(0.3))
    cnn_model.add(Dense(2))
    cnn_model.add(Activation('softmax'))
    cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    acc_history = cnn_model.fit(tf_X, Y1, epochs=3, validation_data=(X_test, y_test))
    predict = cnn_model.predict(X_test)
    prediction_data = np.argmax(predict, axis=1)
    y_test = np.argmax(y_test, axis=1)
    metrics("CNN","TF", y_test, prediction_data)

    X_train, X_test, y_train, y_test = train_test_split(tfidf_X, Y1, test_size=0.3, random_state=0)
    cnn_model = Sequential()
    cnn_model.add(Dense(100, input_shape=(X_train.shape[1],)))
    cnn_model.add(Activation('relu'))
    cnn_model.add(Dropout(0.3))
    cnn_model.add(Dense(100))
    cnn_model.add(Activation('relu'))
    cnn_model.add(Dropout(0.3))
    cnn_model.add(Dense(2))
    cnn_model.add(Activation('softmax'))
    cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    acc_history = cnn_model.fit(tfidf_X, Y1, epochs=3, validation_data=(X_test, y_test))
    predict = cnn_model.predict(X_test)
    prediction_data = np.argmax(predict, axis=1)
    y_test = np.argmax(y_test, axis=1)
    metrics("CNN","TF-IDF", y_test, prediction_data)
